apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: project
  name: todoappwebserver-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todoappwebserver
  template:
    metadata:
      labels:
        app: todoappwebserver
    spec:
      volumes:
        - name: todoapp
          persistentVolumeClaim:
            claimName: my-pv-claim
      containers:
        - name: todoappwebserver
          image: FRONTEND/IMAGE
          imagePullPolicy: Always
          env:
            - name: PORT
              value: "3000"
            - name: TODO_BACKEND_URL
              value: "http://todobackend-svc:4345/todos"
            - name: FORM_URL
              value: "http://localhost:8081/todos"
            - name: FILEPATH
              value: /usr/src/app/files
            - name: IMG_NAME
              value: "current-image"
            - name: IMG_URL
              value: "https://picsum.photos"
            - name: IMG_SIZE_MIN
              value: "0"
            - name: IMG_SIZE_MAX
              value: "5000"
          volumeMounts:
            - name: todoapp
              mountPath: /usr/src/app/files
  strategy:
    type: RollingUpdate