apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: project
  name: todobackend-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todobackend
  template:
    metadata:
      labels:
        app: todobackend
    spec:
      containers:
        - name: todobackend
          image: BACKEND/IMAGE
          imagePullPolicy: Always
          env:
            - name: REDIRECT_URL
              value: "http://localhost:8081"
            - name: PORT
              value: "4040"
          envFrom:
            - configMapRef:
                name: postgres-config
            - secretRef:
                name: postgres-secret
          resources:
            requests:
              memory: "32Mi"
              cpu: "200m"
            limits:
              memory: "64Mi"
              cpu: "250m"