apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: project
  name: todobackend-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todobackend
  template:
    metadata:
      labels:
        app: todobackend
    spec:
      containers:
        - name: todobackend
          image: BACKEND/IMAGE
          imagePullPolicy: Always
          env:
            - name: REDIRECT_URL
              value: "http://localhost:8081"
            - name: PORT
              value: "4040"
            - name: NATS_HOST
              value: "nats://my-nats:4222"
            - name: TODO_CREATED_SUBJECT
              value: "todo_created"
            - name: TODO_COMPLETED_SUBJECT
              value: "todo_completed"
          envFrom:
            - configMapRef:
                name: postgres-config
            - secretRef:
                name: postgres-secret
          readinessProbe:
            httpGet:
              path: /actuator/health/db
              port: 4040
            initialDelaySeconds: 20
            periodSeconds: 5
            failureThreshold: 3
          livenessProbe:
            initialDelaySeconds: 40
            periodSeconds: 5
            httpGet:
              path: /actuator/health/db
              port: 4040