apiVersion: v1
kind: ConfigMap
metadata:
  namespace: project
  name: postgres-config
data:
  DATABASE_URL: "postgres-project-svc"
  DATABASE_PORT: "5432"
  DATABASE_NAME: "todo_db"
  DATABASE_USERNAME: "postgres"