apiVersion: apps/v1
kind: Deployment
metadata:
  name: logoutput-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logoutput
  template:
    metadata:
      labels:
        app: logoutput
    spec:
      volumes:
        - name: shared-log
          emptyDir: {}
      containers:
        - name: logoutput
          image: wilky2/logoutput:2.1
          volumeMounts:
            - name: shared-log
              mountPath: /usr/src/app/files
          env:
            - name: PINGPONG_URL
              value: "http://pingpong-svc:4234/value"
        - name: logoutputfile
          image: wilky2/logoutputfile:2.1
          volumeMounts:
            - name: shared-log
              mountPath: /usr/src/app/files