apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: exercises
  name: pingpong-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pingpong
  template:
    metadata:
      labels:
        app: pingpong
    spec:
      volumes:
        - name: shared-log
          emptyDir: {}
      containers:
        - name: pingpong
          image: wilky2/pingpong:4.1
          imagePullPolicy: Always
          env:
            - name: PORT
              value: "4040"
            - name: DATABASE_URL
              value: "postgres-svc"
            - name: DATABASE_PORT
              value: "5432"
            - name: DATABASE_NAME
              value: "pong_db"
            - name: DATABASE_USERNAME
              value: "postgres"
            - name: DATABASE_PASSWORD
              value: "postgres"
          volumeMounts:
            - name: shared-log
              mountPath: /usr/src/app/files
          readinessProbe:
            httpGet:
              path: /actuator/health/db
              port: 4040
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 5