apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: exercises
  name: pingpong-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pingpong
  template:
    metadata:
      labels:
        app: pingpong
    spec:
      volumes:
        - name: shared-log
          emptyDir: {}
      containers:
        - name: pingpong
          image: wilky2/pingpong:2.1
          env:
            - name: PORT
              value: "4040"
          volumeMounts:
            - name: shared-log
              mountPath: /usr/src/app/files