apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: pingpong-rollout
  namespace: exercises
spec:
  replicas: 4
  selector:
    matchLabels:
      app: pingpong
  strategy:
    canary:
      steps:
        - setWeight: 50
        - analysis:
            templates:
              - templateName: pingpong-cpu-usage
  template:
    metadata:
      labels:
        app: pingpong
    spec:
      volumes:
        - name: shared-log
          emptyDir: {}
      containers:
        - name: pingpong
          image: PINGPONG/IMAGE
          imagePullPolicy: Always
          env:
            - name: PORT
              value: "4040"
            - name: DATABASE_URL
              value: "postgres-svc"
            - name: DATABASE_PORT
              value: "5432"
            - name: DATABASE_NAME
              value: "pong_db"
            - name: DATABASE_USERNAME
              value: "postgres"
            - name: DATABASE_PASSWORD
              value: "postgres"
          volumeMounts:
            - name: shared-log
              mountPath: /usr/src/app/files
          readinessProbe:
            httpGet:
              path: /actuator/health/db
              port: 4040
            initialDelaySeconds: 20
            periodSeconds: 5
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: /actuator/health/db
              port: 4040
            initialDelaySeconds: 40
            periodSeconds: 5
            failureThreshold: 5
