spring.application.name: todo-backend

server.port: ${PORT}

redirect.url: ${REDIRECT_URL}

spring:
  datasource:
    url: jdbc:postgresql://${DATABASE_URL}:${DATABASE_PORT}/${DATABASE_NAME}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate.ddl-auto: update

nats:
  host: ${NATS_HOST}

subject:
  created: ${TODO_CREATED_SUBJECT}
  completed: ${TODO_COMPLETED_SUBJECT}

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always