apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pv-claim
  namespace: project
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi  # minimum allowed on GKE Persistent Disk
  storageClassName: standard-rwo
