apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - volume/manifests/persistentvolumeclaim.yaml
  - postgres-db/manifests/postgres-statefulset.yaml
  - postgres-db/manifests/postgres-svc.yaml
  - todo-app-web-server/manifests/deployment.yaml
  - todo-app-web-server/manifests/gateway.yaml
  - todo-app-web-server/manifests/route.yaml
  - todo-app-web-server/manifests/route-image.yaml
  - todo-app-web-server/manifests/service.yaml
  - todo-backend/manifests/deployment.yaml
  - todo-backend/manifests/service.yaml
  - todo-backend/manifests/route.yaml
  - todo-backend/manifests/postgres-config.yaml
  - todo-backend/manifests/postgres-secret.yaml
  - todo-backend/manifests/wikipedia-todo-cronjob.yaml
images:
  - name: FRONTEND/IMAGE
    newName: wilky2/todoappwebserver:2.8
  - name: BACKEND/IMAGE
    newName: wilky2/todobackend:2.10