apiVersion: v1
kind: Service
metadata:
  namespace: project
  name: postgres-project-svc
  labels:
    app: postgres
spec:
  ports:
  - port: 5432
    name: database
  clusterIP: None
  selector:
    app: postgresdb