apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: project
  name: postgres-project-stset
spec:
  serviceName: postgres-project-svc
  replicas: 1
  selector:
    matchLabels:
      app: postgresdb
  template:
    metadata:
      labels:
        app: postgresdb
    spec:
      containers:
        - name: postgres
          image: postgres:18rc1-alpine3.22
          env:
            - name: POSTGRES_DB
              value: "todo_db"
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "postgres"
          ports:
            - name: database
              containerPort: 5432
          volumeMounts:
            - name: postgres-project-data-storage
              mountPath: /var/lib/postgresql/18/docker
  volumeClaimTemplates:
    - metadata:
        name: postgres-project-data-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: local-path
        resources:
          requests:
            storage: 100Mi