apiVersion: batch/v1
kind: CronJob
metadata:
  name: postgres-backup
  namespace: project
spec:
  schedule: "0 2 * * *"   # every day at 2 AM
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: backup
              image: google/cloud-sdk:slim   # includes gsutil
              envFrom:
                - secretRef:
                    name: postgres-backup-secret
              volumeMounts:
                - name: gcs-key
                  mountPath: /secrets
                  readOnly: true
              command:
                - /bin/sh
                - -c
                - |
                  export GOOGLE_APPLICATION_CREDENTIALS="/secrets/gcp-key.json"
                  TIMESTAMP=$(date +%Y%m%d-%H%M%S)
                  PGPASSWORD=$POSTGRES_PASSWORD pg_dump \
                    -h postgres-project-svc \
                    -U $POSTGRES_USER \
                    -d $POSTGRES_DB \
                    > /tmp/todo_db-$TIMESTAMP.sql
                  gsutil cp /tmp/todo_db-$TIMESTAMP.sql gs://wilkybucket/backups/
          restartPolicy: OnFailure
          volumes:
            - name: gcs-key
              secret:
                secretName: gcs-key
