spring.application.name: todo-app-web-server

server.port: ${PORT}

todobackend: ${TODO_BACKEND_URL}
form.url: ${FORM_URL}

img:
  path: ${FILEPATH}
  name: ${IMG_NAME}
  url: ${IMG_URL}
  size:
    min: ${IMG_SIZE_MIN}
    max: ${IMG_SIZE_MAX}

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always