name: Cleanup Environment

on:
  delete:   # Triggered when a branch or tag is deleted
    branches:
      - '*' # Listen to all branch deletions

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: dwk-cluster
  GKE_ZONE: europe-north1-b

jobs:
  cleanup:
    name: cleanup
    runs-on: ubuntu-latest
    environment: todoapp

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GKE_SA_KEY }}'

      - name: 'Set up Cloud SDK'
        uses: google-github-actions/setup-gcloud@v2

      - name: 'Use gcloud CLI'
        run: gcloud info

      - name: 'Get GKE credentials'
        uses: 'google-github-actions/get-gke-credentials@v2'
        with:
          cluster_name: '${{ env.GKE_CLUSTER }}'
          project_id: '${{ env.PROJECT_ID }}'
          location: '${{ env.GKE_ZONE }}'

      - name: Cleanup
        run: |
          if [ "${GITHUB_REF#refs/heads/}" = "master" ]; then
            NAMESPACE="project"
          else
            NAMESPACE="${GITHUB_REF#refs/heads/}"
          fi
          
          echo %NAMESPACE

          kubectl delete namespace $NAMESPACE --ignore-not-found=true