name: Build and publish application

on:
  push:

jobs:
  build-publish:
    name: Build, Push, Release
    runs-on: ubuntu-latest
    environment: docker

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # tag image with the GitHub SHA to get a unique tag
      - name: Build and publish backend
        run: |-
          docker build ./logoutput/log-output-app --tag "wilky2/logoutput:$GITHUB_SHA"
          docker push "wilky2/logoutput:$GITHUB_SHA"
          docker build ./logoutput/ping-pong-app --tag "wilky2/pingpong:$GITHUB_SHA"
          docker push "wilky2/pingpong:$GITHUB_SHA"

      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v2

      - name: Use right image
        run: |
          cd logoutput
          kustomize edit set image LOGOUTPUT/IMAGE=wilky2/logoutput:$GITHUB_SHA PINGPONG/IMAGE=wilky2/pingpong:$GITHUB_SHA
        
      - name: commit kustomization.yaml to GitHub
        uses: EndBug/add-and-commit@v9
        with:
          add: './logoutput/kustomization.yaml'
          message: New version released ${{ github.sha }}