name: Build and publish application

on:
  push:
    paths:
      - "todo-app/**"
      - ".github/workflows/todo.yml"
      - "!todo-app/kustomization.yaml"
      - "!todo-app/README.md"

jobs:
  build-publish:
    name: Build, Push, Release
    runs-on: ubuntu-latest
    environment: docker

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # tag image with the GitHub SHA to get a unique tag
      - name: Build and publish backend
        run: |-
          docker build ./todo-app/todo-app-web-server --tag "wilky2/todoappwebserver:$GITHUB_SHA"
          docker push "wilky2/todoappwebserver:$GITHUB_SHA"
          docker build ./todo-app/todo-backend --tag "wilky2/todobackend:$GITHUB_SHA"
          docker push "wilky2/todobackend:$GITHUB_SHA"
          docker build ./todo-app/broadcast --tag "wilky2/broadcast:$GITHUB_SHA"
          docker push "wilky2/broadcast:$GITHUB_SHA"

      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v2

      - name: Use right image
        run: |
          cd todo-app
          kustomize edit set image FRONTEND/IMAGE=wilky2/todoappwebserver:$GITHUB_SHA BACKEND/IMAGE=wilky2/todobackend:$GITHUB_SHA BROADCAST/IMAGE=wilky2/broadcast:$GITHUB_SHA
        
      - name: commit kustomization.yaml to GitHub
        uses: EndBug/add-and-commit@v9
        with:
          add: './todo-app/kustomization.yaml'
          message: New version released ${{ github.sha }}